var test__bus__data__calculations_8py =
[
    [ "Zaliczeniowy_autobusy.BusTracker.tests.test_bus_data_calculations.TestBusDataCalculations", "classZaliczeniowy__autobusy_1_1BusTracker_1_1tests_1_1test__bus__data__calculations_1_1TestBusDataCalculations.html", "classZaliczeniowy__autobusy_1_1BusTracker_1_1tests_1_1test__bus__data__calculations_1_1TestBusDataCalculations" ]
];