@startuml


object VehicleData {
  Lines = 213
  Lon = 21.220171
  VehicleNumber = "1011"
  Time = "2024-01-17 19:36:38"
  Lat = 52.157358
  Brigade = 3
}

object BusStopData {
  zespol = 1002
  slupek = "03"
  nazwa_zespolu = "Ząbkowska"
  id_ulicy = 2201
  szer_geo = 52.251583
  dlug_geo = 21.038448
  kierunek = "Kijowska"
  obowiazuje_od = "2023-09-16 00:00:00.0"
}


VehicleData --> BusStopData : "Compares Lat/Lon with szer_geo/dlug_geo"

@enduml
