@startuml
    actor Downloader
    actor Processor
    actor Calculator
    actor Analytics
    actor Output

    Downloader -> Downloader : Active for 7200 sec
    Downloader -> Downloader : Inactive

    Processor -> Processor : Active for 30 sec
    Processor -> Processor : Inactive

    Calculator -> Calculator : Active for 20 sec
    Calculator -> Calculator : Inactive

    Analytics -> Analytics : Active for 15 sec
    Analytics -> Analytics : Inactive

    Output -> Output : Active for 0.1 sec
    Output -> Output : Inactive
@enduml
