var searchData=
[
  ['save_5fresults_0',['save_results',['../bus__data__utils_8py.html#ac9ba5b44b021eae88f13a4867fda9359',1,'Zaliczeniowy_autobusy::BusTracker::utils::bus_data_utils']]],
  ['setup_1',['setUp',['../class_zaliczeniowy__autobusy_1_1_bus_tracker_1_1tests_1_1test__bus__data__calculations_1_1_test_bus_data_calculations.html#a96bdff078cf2a8c07a418ecde4031f50',1,'Zaliczeniowy_autobusy.BusTracker.tests.test_bus_data_calculations.TestBusDataCalculations.setUp()'],['../class_zaliczeniowy__autobusy_1_1_bus_tracker_1_1tests_1_1test__speed__checker_1_1_test___speed___violation.html#a035bd5465aeb31fcb9327f849a8b3946',1,'Zaliczeniowy_autobusy.BusTracker.tests.test_speed_checker.Test_Speed_Violation.setUp()']]],
  ['simple_20stupid_2',['4. Простота (KISS - Keep It Simple, Stupid)',['../index.html#autotoc_md5',1,'']]],
  ['single_20responsibility_20і_20dependency_20inversion_3',['8. SOLID (особливо принципи &quot;Single Responsibility&quot; і &quot;Dependency Inversion&quot;)',['../index.html#autotoc_md9',1,'']]],
  ['single_20responsibility_20principle_20_3a_20strong_4',['&lt;strong&gt;Розподіл відповідальностей (Single Responsibility Principle):&lt;/strong&gt;',['../index.html#autotoc_md28',1,'']]],
  ['solid_20особливо_20принципи_20single_20responsibility_20і_20dependency_20inversion_5',['8. SOLID (особливо принципи &quot;Single Responsibility&quot; і &quot;Dependency Inversion&quot;)',['../index.html#autotoc_md9',1,'']]],
  ['speed_5fcalculation_5ffactory_2epy_6',['speed_calculation_factory.py',['../speed__calculation__factory_8py.html',1,'']]],
  ['speed_5fcalculation_5fstrategy_2epy_7',['speed_calculation_strategy.py',['../speed__calculation__strategy_8py.html',1,'']]],
  ['speed_5fviolation_5fchecker_2epy_8',['speed_violation_checker.py',['../speed__violation__checker_8py.html',1,'']]],
  ['speed_5fviolation_5ffactory_2epy_9',['speed_violation_factory.py',['../speed__violation__factory_8py.html',1,'']]],
  ['speedcalculationfactory_10',['SpeedCalculationFactory',['../class_zaliczeniowy__autobusy_1_1_bus_tracker_1_1data__processing_1_1speed__calculation__factory_1_1_speed_calculation_factory.html',1,'Zaliczeniowy_autobusy::BusTracker::data_processing::speed_calculation_factory']]],
  ['speedcalculationfactory_20strong_20фабрика_20обчислення_20швидкості_11',['&lt;strong&gt;SpeedCalculationFactory&lt;/strong&gt; (Фабрика обчислення швидкості)',['../index.html#autotoc_md19',1,'']]],
  ['speedcalculationstrategy_12',['SpeedCalculationStrategy',['../class_zaliczeniowy__autobusy_1_1_bus_tracker_1_1data__processing_1_1speed__calculation__strategy_1_1_speed_calculation_strategy.html',1,'Zaliczeniowy_autobusy::BusTracker::data_processing::speed_calculation_strategy']]],
  ['speedviolationchecker_13',['SpeedViolationChecker',['../class_zaliczeniowy__autobusy_1_1_bus_tracker_1_1data__processing_1_1speed__violation__checker_1_1_speed_violation_checker.html',1,'Zaliczeniowy_autobusy::BusTracker::data_processing::speed_violation_checker']]],
  ['speedviolationchecker_20strong_20перевірка_20порушень_20швидкості_14',['&lt;strong&gt;SpeedViolationChecker&lt;/strong&gt; (Перевірка порушень швидкості)',['../index.html#autotoc_md17',1,'']]],
  ['speedviolationcheckerfactory_15',['SpeedViolationCheckerFactory',['../class_zaliczeniowy__autobusy_1_1_bus_tracker_1_1data__processing_1_1speed__violation__factory_1_e644eba1d9429471f51caa8790b68015.html',1,'Zaliczeniowy_autobusy::BusTracker::data_processing::speed_violation_factory']]],
  ['speedviolationcheckerfactory_20strong_20фабрика_20порушень_20швидкості_16',['&lt;strong&gt;SpeedViolationCheckerFactory&lt;/strong&gt; (Фабрика порушень швидкості)',['../index.html#autotoc_md18',1,'']]],
  ['stop_5futils_2epy_17',['stop_utils.py',['../stop__utils_8py.html',1,'']]],
  ['strategy_20pattern_20_3a_20strong_18',['&lt;strong&gt;Патерн &quot;Стратегія&quot; (Strategy Pattern):&lt;/strong&gt;',['../index.html#autotoc_md26',1,'']]],
  ['strong_19',['strong',['../md_glossary.html',1,'Глосарій термінів проєкту &lt;strong&gt;BusTracker&lt;/strong&gt;'],['../index.html#autotoc_md30',1,'&lt;strong&gt;Інкапсуляція (Encapsulation):&lt;/strong&gt;'],['../index.html#autotoc_md32',1,'&lt;strong&gt;Зниження зв&apos;язності (Loose Coupling):&lt;/strong&gt;'],['../index.html#autotoc_md33',1,'&lt;strong&gt;Масштабованість:&lt;/strong&gt;'],['../index.html#autotoc_md26',1,'&lt;strong&gt;Патерн &quot;Стратегія&quot; (Strategy Pattern):&lt;/strong&gt;'],['../index.html#autotoc_md27',1,'&lt;strong&gt;Патерн &quot;Фабрика&quot; (Factory Pattern):&lt;/strong&gt;'],['../index.html#autotoc_md29',1,'&lt;strong&gt;Принцип відкритості/закритості (Open/Closed Principle):&lt;/strong&gt;'],['../index.html#autotoc_md28',1,'&lt;strong&gt;Розподіл відповідальностей (Single Responsibility Principle):&lt;/strong&gt;'],['../index.html#autotoc_md31',1,'&lt;strong&gt;Тестування:&lt;/strong&gt;']]],
  ['strong_20інкапсуляція_20encapsulation_20_3a_20strong_20',['&lt;strong&gt;Інкапсуляція (Encapsulation):&lt;/strong&gt;',['../index.html#autotoc_md30',1,'']]],
  ['strong_20аналіз_20пунктуальності_21',['&lt;strong&gt;PunctualityAnalyzer&lt;/strong&gt; (Аналіз пунктуальності)',['../index.html#autotoc_md20',1,'']]],
  ['strong_20географічні_20утиліти_22',['&lt;strong&gt;GeoUtils&lt;/strong&gt; (Географічні утиліти)',['../index.html#autotoc_md23',1,'']]],
  ['strong_20зниження_20зв_20язності_20loose_20coupling_20_3a_20strong_23',['&lt;strong&gt;Зниження зв&apos;язності (Loose Coupling):&lt;/strong&gt;',['../index.html#autotoc_md32',1,'']]],
  ['strong_20кластеризація_20порушень_20швидкості_24',['&lt;strong&gt;ViolationClusterer&lt;/strong&gt; (Кластеризація порушень швидкості)',['../index.html#autotoc_md21',1,'']]],
  ['strong_20масштабованість_3a_20strong_25',['&lt;strong&gt;Масштабованість:&lt;/strong&gt;',['../index.html#autotoc_md33',1,'']]],
  ['strong_20обробка_20даних_20автобусів_26',['&lt;strong&gt;BusDataHandler&lt;/strong&gt; (Обробка даних автобусів)',['../index.html#autotoc_md16',1,'']]],
  ['strong_20основний_20модуль_27',['&lt;strong&gt;Main&lt;/strong&gt; (Основний модуль)',['../index.html#autotoc_md24',1,'']]],
  ['strong_20патерн_20стратегія_20strategy_20pattern_20_3a_20strong_28',['&lt;strong&gt;Патерн &quot;Стратегія&quot; (Strategy Pattern):&lt;/strong&gt;',['../index.html#autotoc_md26',1,'']]],
  ['strong_20патерн_20фабрика_20factory_20pattern_20_3a_20strong_29',['&lt;strong&gt;Патерн &quot;Фабрика&quot; (Factory Pattern):&lt;/strong&gt;',['../index.html#autotoc_md27',1,'']]],
  ['strong_20перевірка_20порушень_20швидкості_30',['&lt;strong&gt;SpeedViolationChecker&lt;/strong&gt; (Перевірка порушень швидкості)',['../index.html#autotoc_md17',1,'']]],
  ['strong_20принцип_20відкритості_20закритості_20open_20closed_20principle_20_3a_20strong_31',['&lt;strong&gt;Принцип відкритості/закритості (Open/Closed Principle):&lt;/strong&gt;',['../index.html#autotoc_md29',1,'']]],
  ['strong_20розподіл_20відповідальностей_20single_20responsibility_20principle_20_3a_20strong_32',['&lt;strong&gt;Розподіл відповідальностей (Single Responsibility Principle):&lt;/strong&gt;',['../index.html#autotoc_md28',1,'']]],
  ['strong_20тестування_3a_20strong_33',['&lt;strong&gt;Тестування:&lt;/strong&gt;',['../index.html#autotoc_md31',1,'']]],
  ['strong_20утиліти_20для_20роботи_20з_20api_34',['&lt;strong&gt;APIUtils&lt;/strong&gt; (Утиліти для роботи з API)',['../index.html#autotoc_md22',1,'']]],
  ['strong_20фабрика_20обчислення_20швидкості_35',['&lt;strong&gt;SpeedCalculationFactory&lt;/strong&gt; (Фабрика обчислення швидкості)',['../index.html#autotoc_md19',1,'']]],
  ['strong_20фабрика_20порушень_20швидкості_36',['&lt;strong&gt;SpeedViolationCheckerFactory&lt;/strong&gt; (Фабрика порушень швидкості)',['../index.html#autotoc_md18',1,'']]],
  ['strong_20apiutils_20strong_20утиліти_20для_20роботи_20з_20api_37',['&lt;strong&gt;APIUtils&lt;/strong&gt; (Утиліти для роботи з API)',['../index.html#autotoc_md22',1,'']]],
  ['strong_20busdatahandler_20strong_20обробка_20даних_20автобусів_38',['&lt;strong&gt;BusDataHandler&lt;/strong&gt; (Обробка даних автобусів)',['../index.html#autotoc_md16',1,'']]],
  ['strong_20bustracker_20strong_39',['Глосарій термінів проєкту &lt;strong&gt;BusTracker&lt;/strong&gt;',['../md_glossary.html',1,'']]],
  ['strong_20geoutils_20strong_20географічні_20утиліти_40',['&lt;strong&gt;GeoUtils&lt;/strong&gt; (Географічні утиліти)',['../index.html#autotoc_md23',1,'']]],
  ['strong_20main_20strong_20основний_20модуль_41',['&lt;strong&gt;Main&lt;/strong&gt; (Основний модуль)',['../index.html#autotoc_md24',1,'']]],
  ['strong_20punctualityanalyzer_20strong_20аналіз_20пунктуальності_42',['&lt;strong&gt;PunctualityAnalyzer&lt;/strong&gt; (Аналіз пунктуальності)',['../index.html#autotoc_md20',1,'']]],
  ['strong_20speedcalculationfactory_20strong_20фабрика_20обчислення_20швидкості_43',['&lt;strong&gt;SpeedCalculationFactory&lt;/strong&gt; (Фабрика обчислення швидкості)',['../index.html#autotoc_md19',1,'']]],
  ['strong_20speedviolationchecker_20strong_20перевірка_20порушень_20швидкості_44',['&lt;strong&gt;SpeedViolationChecker&lt;/strong&gt; (Перевірка порушень швидкості)',['../index.html#autotoc_md17',1,'']]],
  ['strong_20speedviolationcheckerfactory_20strong_20фабрика_20порушень_20швидкості_45',['&lt;strong&gt;SpeedViolationCheckerFactory&lt;/strong&gt; (Фабрика порушень швидкості)',['../index.html#autotoc_md18',1,'']]],
  ['strong_20violationclusterer_20strong_20кластеризація_20порушень_20швидкості_46',['&lt;strong&gt;ViolationClusterer&lt;/strong&gt; (Кластеризація порушень швидкості)',['../index.html#autotoc_md21',1,'']]],
  ['stupid_47',['4. Простота (KISS - Keep It Simple, Stupid)',['../index.html#autotoc_md5',1,'']]]
];
