var speed__calculation__strategy_8py =
[
    [ "Zaliczeniowy_autobusy.BusTracker.data_processing.speed_calculation_strategy.SpeedCalculationStrategy", "classZaliczeniowy__autobusy_1_1BusTracker_1_1data__processing_1_1speed__calculation__strategy_1_1SpeedCalculationStrategy.html", "classZaliczeniowy__autobusy_1_1BusTracker_1_1data__processing_1_1speed__calculation__strategy_1_1SpeedCalculationStrategy" ],
    [ "Zaliczeniowy_autobusy.BusTracker.data_processing.speed_calculation_strategy.HaversineSpeedCalculationStrategy", "classZaliczeniowy__autobusy_1_1BusTracker_1_1data__processing_1_1speed__calculation__strategy_1_3328aa835c603aa1289754510d3332ac.html", "classZaliczeniowy__autobusy_1_1BusTracker_1_1data__processing_1_1speed__calculation__strategy_1_3328aa835c603aa1289754510d3332ac" ]
];