var test__api__connection_8py =
[
    [ "Zaliczeniowy_autobusy.BusTracker.tests.test_api_connection.TestConnectToAPI", "classZaliczeniowy__autobusy_1_1BusTracker_1_1tests_1_1test__api__connection_1_1TestConnectToAPI.html", "classZaliczeniowy__autobusy_1_1BusTracker_1_1tests_1_1test__api__connection_1_1TestConnectToAPI" ]
];