name: Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  doxygen:
    name: Generate Doxygen Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Doxygen and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen texlive-font-utils

    - name: Run Doxygen
      run: doxygen Zaliczeniowy_autobusy/Doxyfile
  
    - name: Deploy to GitHub Pages
      if: success()
      run: |
        if [ -d html ]; then
          git config --global user.email "katepavlichenko2@gmail.com"
          git config --global user.name "kate"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r html/* .
          git add .
          git commit -m "Deploy Doxygen documentation"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kate20031/Bus_Tracker_Refactored.git gh-pages --force
        else
          echo "No HTML output found. Deployment skipped."
          exit 1
        fi



    - name: Cleanup files (optional)
      if: always()
      run: |
        rm -rf Zaliczeniowy_autobusy/html
        rm -rf Zaliczeniowy_autobusy/latex
        rm -f Zaliczeniowy_autobusy/setup.py
        rm -f requirements.txt
        rm -f setup.py
